#!bin/bash
#
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 10 0
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 10 1
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 10 2
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 10 3
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 10 4
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 10 5
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 10 6
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 10 7
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 10 8
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 10 9
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 30 0
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 30 1
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 30 2
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 30 3
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 30 4
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 30 5
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 30 6
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 30 7
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 30 8
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 30 9
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 50 0
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 50 1
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 50 2
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 50 3
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 50 4
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 50 5
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 50 6
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 50 7
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 50 8
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 50 9
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 70 0
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 70 1
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 70 2
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 70 3
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 70 4
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 70 5
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 70 6
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 70 7
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 70 8
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 70 9
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 90 0
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 90 1
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 90 2
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 90 3
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 90 4
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 90 5
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 90 6
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 90 7
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 90 8
time python transfer_graph_laplacian_outer_parallel_cv.py SanDiego Austin 1 90 9
